### PR TITLE
bmm: verify connection mainchain on startup

### PR DESCRIPTION
**Pull request by torkelrogstad**
There's two commits here. The first one verifies the connection to the mainchain on startup, instead of failing horribly later on in the case of bad config. 

The second commit I'm a bit unsure of: I had to apply these changes to get this to compile. However, I have zero experience with FFI/cgo. Is this because I'm on macos, and this was originally built for Linux? In that case we might need to introduce platform-specific Go files (which is easy, and I can help with that).

### CODE REVIEW

**Comment by nchashch** [comment]
Interestingly with the second commit I can't compile it on my machine, I get:
```
drivechain/drivechain.go:179:13: cannot use _Ctype_ulonglong(deposit.Amount.Uint64()) (value of type _Ctype_ulonglong) as _Ctype_ulong value in struct literal
drivechain/drivechain.go:196:14: cannot use _Ctype_ulonglong(w.Amount.Uint64()) (value of type _Ctype_ulonglong) as _Ctype_ulong value in struct literal
drivechain/drivechain.go:197:14: cannot use _Ctype_ulonglong(w.Fee.Uint64()) (value of type _Ctype_ulonglong) as _Ctype_ulong value in struct literal
drivechain/drivechain.go:212:12: cannot use _Ctype_ulonglong(r.Amount.Uint64()) (value of type _Ctype_ulonglong) as _Ctype_ulong value in struct literal
drivechain/drivechain.go:229:13: cannot use _Ctype_ulonglong(deposit.Amount.Uint64()) (value of type _Ctype_ulonglong) as _Ctype_ulong value in struct literal
drivechain/drivechain.go:277:39: cannot use cAmount (variable of type _Ctype_ulonglong) as _Ctype_ulong value in argument to (_Cfunc_create_deposit)
drivechain/drivechain.go:277:48: cannot use cFee (variable of type _Ctype_ulonglong) as _Ctype_ulong value in argument to (_Cfunc_create_deposit)
drivechain/drivechain.go:362:51: cannot use _Ctype_ulonglong(amount) (value of type _Ctype_ulonglong) as _Ctype_ulong value in argument to (_Cfunc_attempt_bmm)
util.go:47: exit status 1
exit status 1
make: *** [Makefile:14: geth] Error 1
```
I think the problem is that I am using a 64 bit machine and you are using a 32 bit machine.

The bindings.h file generated by drivechain-c uses the `uint64_t` type:
```C
typedef struct Deposit {
  const char *address;
  uint64_t amount;
} Deposit;
```

On a 64 bit machie `uint64_t` is `unsigned long`.
On a 32 bit machie `uint64_t` is `unsigned long long`.
So there is an error because of mismatched types.

**Comment by nchashch** [comment]
I have also updated the `sidechain` branch to use the version of drivechain-c that fixes https://github.com/nchashch/drivechain-c/issues/1, you might want to rebase.

**Comment by torkelrogstad** [comment]
I'm definitely on a 64-bit machine as well! Could be that I'm on ARM architecture? I'm on a Macbook Pro with the M2 chip. What are you on?

**Comment by torkelrogstad** [comment]
Removed the second commit, as my assumptions weren't correct. Also rebased

**Comment by nchashch** [comment]
> I'm definitely on a 64-bit machine as well! Could be that I'm on ARM architecture? I'm on a Macbook Pro with the M2 chip. What are you on?

I am using Arch on an x86-64 machine. I guess uint64_t is also defined differently between ARM / M2 and x86-64.

**Pull request merged**
